/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/kingyoung/catkin_ws/src/serial_pkg/srv/Serial.srv
 *
 */


#ifndef SERIAL_PKG_MESSAGE_SERIAL_H
#define SERIAL_PKG_MESSAGE_SERIAL_H

#include <ros/service_traits.h>


#include <serial_pkg/SerialRequest.h>
#include <serial_pkg/SerialResponse.h>


namespace serial_pkg
{

struct Serial
{

typedef SerialRequest Request;
typedef SerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Serial
} // namespace serial_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serial_pkg::Serial > {
  static const char* value()
  {
    return "77e4bd5ab3181f65a110283ab4ab9176";
  }

  static const char* value(const ::serial_pkg::Serial&) { return value(); }
};

template<>
struct DataType< ::serial_pkg::Serial > {
  static const char* value()
  {
    return "serial_pkg/Serial";
  }

  static const char* value(const ::serial_pkg::Serial&) { return value(); }
};


// service_traits::MD5Sum< ::serial_pkg::SerialRequest> should match 
// service_traits::MD5Sum< ::serial_pkg::Serial > 
template<>
struct MD5Sum< ::serial_pkg::SerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serial_pkg::Serial >::value();
  }
  static const char* value(const ::serial_pkg::SerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_pkg::SerialRequest> should match 
// service_traits::DataType< ::serial_pkg::Serial > 
template<>
struct DataType< ::serial_pkg::SerialRequest>
{
  static const char* value()
  {
    return DataType< ::serial_pkg::Serial >::value();
  }
  static const char* value(const ::serial_pkg::SerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serial_pkg::SerialResponse> should match 
// service_traits::MD5Sum< ::serial_pkg::Serial > 
template<>
struct MD5Sum< ::serial_pkg::SerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serial_pkg::Serial >::value();
  }
  static const char* value(const ::serial_pkg::SerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serial_pkg::SerialResponse> should match 
// service_traits::DataType< ::serial_pkg::Serial > 
template<>
struct DataType< ::serial_pkg::SerialResponse>
{
  static const char* value()
  {
    return DataType< ::serial_pkg::Serial >::value();
  }
  static const char* value(const ::serial_pkg::SerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_PKG_MESSAGE_SERIAL_H
