controller_frequency: 15
planner_frequency: 1.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.4
  #max_vel_x: 0.3
   min_vel_x: 0.10
   max_rotational_vel: 0.8
   min_in_place_vel_theta: 0.3
   escape_vel: -0.1
   acc_lim_x: 1.0
   acc_lim_y: 1.0
   acc_lim_theta: 0.6

   holonomic_robot: false

   yaw_goal_tolerance: 0.2 # about 11 degrees
   xy_goal_tolerance: 0.15  # 10 cm
   latch_xy_goal_tolerance: false

   pdist_scale: 1.8
   gdist_scale: 0.6
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 2.0
   sim_granularity: 0.04
   angular_sim_granularity: 0.04
   vx_samples: 12
   vtheta_samples: 25
   dwa: true
   simple_attractor: false
