local_costmap:
#  track_unknown_space: true
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 6.0
   publish_frequency: 1.0
   inflation_radius: 0.12
   cost_scaling_factor: 10.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 0.5
   map_type: costmap

   plugins:
     - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}

